-- MySQL Script generated by MySQL Workbench
-- Thu Apr 10 20:29:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dg`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci ;
USE `dg` ;

-- -----------------------------------------------------
-- Table `dg`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dg`.`docente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(200) NULL,
  `data_nascimento` DATE NULL,
  `matricula` VARCHAR(10) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `data_admissao` DATE NOT NULL,
  `regime_juridico` VARCHAR(15) NULL,
  `regime_trabalho` VARCHAR(15) NULL,
  `regime_data_aplicacao` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_docente_matricula` (`matricula` ASC) VISIBLE,
  UNIQUE INDEX `uq_docente_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dg`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dg`.`cargo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(60) NOT NULL,
  `funcao` VARCHAR(60) NULL,
  `data_inicio` DATE NOT NULL,
  `referencia` VARCHAR(45) NULL,
  `docente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cargo_docente1_idx` (`docente_id` ASC) VISIBLE,
  CONSTRAINT `fk_cargo_docente1`
    FOREIGN KEY (`docente_id`)
    REFERENCES `dg`.`docente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dg`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dg`.`telefone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(15) NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `docente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_telefone_docente_numero` (`docente_id` ASC, `telefone` ASC) VISIBLE,
  INDEX `fk_telefone_docentes1_idx` (`docente_id` ASC) VISIBLE,
  CONSTRAINT `fk_telefone_docentes1`
    FOREIGN KEY (`docente_id`)
    REFERENCES `dg`.`docente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dg`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dg`.`documentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(25) NOT NULL,
  `documento` VARCHAR(45) NOT NULL,
  `docente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_documentos_tipo_numero` (`tipo` ASC, `documento` ASC) VISIBLE,
  INDEX `fk_documentos_docente1_idx` (`docente_id` ASC) VISIBLE,
  CONSTRAINT `fk_documentos_docente1`
    FOREIGN KEY (`docente_id`)
    REFERENCES `dg`.`docente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dg`.`conta_bancaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dg`.`conta_bancaria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `banco` CHAR(3) NOT NULL,
  `agencia` VARCHAR(8) NOT NULL,
  `conta` VARCHAR(15) NOT NULL,
  `docente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_conta_bancaria_docente_conta` (`docente_id` ASC, `banco` ASC, `agencia` ASC, `conta` ASC) VISIBLE,
  INDEX `fk_conta_bancaria_docente1_idx` (`docente_id` ASC) VISIBLE,
  CONSTRAINT `fk_conta_bancaria_docente1`
    FOREIGN KEY (`docente_id`)
    REFERENCES `dg`.`docente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
