-- MySQL Script generated by MySQL Workbench
-- Thu Apr  3 19:35:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dg
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dg` ;

-- -----------------------------------------------------
-- Schema dg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dg` ;
USE `dg` ;

-- -----------------------------------------------------
-- Table `dg`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dg`.`docente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `endereco` VARCHAR(200) NULL,
  `data_nascimento` DATE NULL,
  `email` VARCHAR(80) NULL,
  `data_admissao` DATE NULL,
  `regime_juridico` VARCHAR(15) NULL,
  `regime_trabalho` VARCHAR(15) NULL,
  `regime_data_aplicacao` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dg`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dg`.`cargo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(60) NOT NULL,
  `data_cargo` DATE NULL,
  `matricula` VARCHAR(10) NULL,
  `referencia` VARCHAR(45) NULL,
  `docente_id` INT NOT NULL,
  PRIMARY KEY (`id`, `docente_id`),
  INDEX `fk_cargo_docente1_idx` (`docente_id` ASC) VISIBLE,
  CONSTRAINT `fk_cargo_docente1`
    FOREIGN KEY (`docente_id`)
    REFERENCES `dg`.`docente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dg`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dg`.`telefone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(11) NOT NULL,
  `tipo` VARCHAR(20) NULL,
  `docente_id` INT NOT NULL,
  PRIMARY KEY (`id`, `docente_id`),
  INDEX `fk_telefone_docentes1_idx` (`docente_id` ASC) VISIBLE,
  CONSTRAINT `fk_telefone_docentes1`
    FOREIGN KEY (`docente_id`)
    REFERENCES `dg`.`docente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dg`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dg`.`documentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(25) NULL,
  `documento` VARCHAR(45) NULL,
  `docente_id` INT NOT NULL,
  PRIMARY KEY (`id`, `docente_id`),
  INDEX `fk_documentos_docente1_idx` (`docente_id` ASC) VISIBLE,
  CONSTRAINT `fk_documentos_docente1`
    FOREIGN KEY (`docente_id`)
    REFERENCES `dg`.`docente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dg`.`conta_bancaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dg`.`conta_bancaria` (
  `id` INT NOT NULL,
  `banco` VARCHAR(3) NULL,
  `agencia` VARCHAR(8) NULL,
  `conta` VARCHAR(15) NULL,
  `docente_id` INT NOT NULL,
  PRIMARY KEY (`id`, `docente_id`),
  INDEX `fk_conta_bancaria_docente1_idx` (`docente_id` ASC) VISIBLE,
  CONSTRAINT `fk_conta_bancaria_docente1`
    FOREIGN KEY (`docente_id`)
    REFERENCES `dg`.`docente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
